In [ ]:
print("Hello")

Hello

used for:
web development (server-side),
software development,
mathematics,
system scripting.

What can Python do?
Python can be used on a server to create web applications.
Python can be used alongside software to create workflows.
Python can connect to database systems. It can also read and modify files.
Python can be used to handle big data and perform complex mathematics.
Python can be used for rapid prototyping, or for production-ready software development.

Python works on different platforms (Windows, Mac, Linux, Raspberry Pi, etc).
Python can be treated in a procedural way, an object-oriented way or a functional way.Python relies on indentation, using whitespace, to define scope; such as the scope of loops, functions and classes. Other programming languages often use curly-brackets for this purpose.

In [ ]:
if 5>2:
  print("5 is bigger")
else:
  print("smaller")
  # this is a comment statemnet used to put comment 
  """ triplle quotes can be used to 
  represent comments for multiple lines"""

5 is bigger

In [ ]:
x =5
y =int(10)
z ="hello"
a ="yup"
b =float(10)
type(y)
# print(x)
# print(y)
print(b)

10.0

In [ ]:
#possible variable formats:
myvar = "John"
my_var = "John"
_my_var = "John"
myVar = "John"
MYVAR = "John"
myvar2 = "John"

Camel Case
Each word, except the first, starts with a capital letter:
Pascal Case
Each word starts with a capital letter:
Snake Case
Each word is separated by an underscore character:

In [ ]:
x, y, z = "Orange", "Banana", "Cherry"
x = y =z ="apple"

In [ ]:
fruits = ["alpha","beta","gamma"]
x,y,z = fruits
print(x,y,z)

alpha beta gamma

In [ ]:
a = "hello"
b = "world"
print(a+b)

x ="hello "
y = "world"
print(x+y)

helloworld
hello world

In [ ]:
# both string and int cant be concatenated like
# if string it will be concatenated or in case of addition,floator other data types it will added
a = 5
b="hell"
print(a+b)

TypeError: ignored

Text Type:	str

Numeric Types:	int, float, complex, complex refers both integer and string 

Sequence Types:	list, tuple, range

Mapping Type:	dict

Set Types:	set, frozenset

Boolean Type:	bool

Binary Types:	bytes, bytearray, memoryview

In [ ]:
a = "string"
b = 5 #int
c = 10.0# float
d = 1j#complex
f = ["hello","world"] #list
g = ("hello","world") #tuple
e = range(6) #range
h = {h1:"hello",h2:"world"} #dict
i = {"hello","world"} #set
j = frozenset({"hello","world"})#frozenset
k = True #bool
l = b"hello"#bytes
m = bytearrray(5)#bytearray
n = memorysize(5)#memorysize

Int, or integer, is a whole number, positive or negative, without decimals, of unlimited length

Float, or "floating point number" is a number, positive or negative, containing one or more decimals.

Float can also be scientific numbers with an "e" to indicate the power of 10.

Complex numbers are written with a "j" as the imaginary part:

In [ ]:
x =10
print(complex(x))
print(type(complex(x)))

import random

print(random.randrange(1, 10))

(10+0j)
<class 'complex'>
7

int() - constructs an integer number from an integer literal, a float literal (by removing all decimals), or a string literal (providing the string represents a whole number)

float() - constructs a float number from an integer literal, a float literal or a string literal (providing the string represents a float or an integer)

str() - constructs a string from a wide variety of data types, including strings, integer literals and float literals

In [ ]:
a ="hello"
for x in a:
  print(x)
print(a[1])
print(len(a))
txt ="hello world"
if a in txt:
  print("present")
if a not in txt:
  print("not present")

h
e
l
l
o
e
5
present

In [ ]:
# Slicing
b = "alpha_beta_gamma"
print(b[0:5])
print(b[:5])
print(b[2:])

alpha
alpha
pha_beta_gamma

The strip() method removes any whitespace from the beginning or the end:

The replace() method replaces a string with another string:

In [ ]:
a = "Hello, World!"
print(a.split(","))
print(a.replace("H", "J"))
quantity = 3
itemno = 567
price = 49.95
myorder = "I want to pay {2} dollars for {0} pieces of item {1}."
print(myorder.format(quantity, itemno, price))

['Hello', ' World!']
Jello, World!
I want to pay 49.95 dollars for 3 pieces of item 567.

In [ ]:
print(bool("abc"))
print(bool(123))
print(bool(["apple", "cherry", "banana"]))
print(bool(False))
print(bool(None))
print(bool(0))
print(bool(""))
print(bool(()))
print(bool([]))
print(bool({}))

def myFunction() :
  return True

if myFunction():
  print("YES!")
else:
  print("NO!")

True
True
True
False
False
False
False
False
False
False
YES!

is 	Returns True if both variables are the same object

is not	Returns True if both variables are not the same object

in 	Returns True if a sequence with the specified value is present in the object


not in	Returns True if a sequence with the specified value is not present in the object

& AND # X&Y
| OR  # X|Y
^ XOR # X^Y
~ NOT # ~X   reverses all the bits
<< Bitwise left
>> Bitwise right

List is a collection which is ordered and changeable. Allows duplicate members.

Tuple is a collection which is ordered and unchangeable. Allows duplicate members.

Set is a collection which is unordered, unchangeable*, and unindexed. No duplicate members.

Dictionary is a collection which is ordered** and changeable. No duplicate members.

In [ ]:
thislist = ["apple", "banana", "cherry"]
thislist.insert(2, "watermelon")
print(thislist)
thislist[1:3] = ["watermelon"]
print(thislist)
thislist.append("orange")
print(thislist)
tropical = ["mango", "pineapple", "papaya"]
thislist.extend(tropical)
print(thislist)

thislist.remove("banana")
thislist.pop(1)
thislist.pop()
del thislist
thislist.clear()
print(thislist)

['apple', 'banana', 'watermelon', 'cherry']
['apple', 'watermelon', 'cherry']
['apple', 'watermelon', 'cherry', 'orange']
['apple', 'watermelon', 'cherry', 'orange', 'mango', 'pineapple', 'papaya']

ValueError: ignored

In [ ]:
#list comprehension representing in short form
fruits=["apple","banana","carrot"]
newlist= [i for i in fruits if"a" in i]

In [ ]:
thislist=["hello","world"]
thislist.sort()
print(thislist)
thislist.sort(reverse =True)

['hello', 'world']

In [ ]:
#customizable sorting
def myfunc(n):
  return abs(n -50)
thislist=[100,50,35,58,22]
thislist.sort(key =myfunc)
print(thislist)
#By default the sort() method is case sensitive, 
#resulting in all capital letters being sorted before lower case letters:
thislist.sort(key = str.lower)#incase if you want everythin to be in lower
thislist.reverse()
print(thislist)

[50, 58, 35, 22, 100]

In [ ]:
list1 = ["a", "b", "c"]
list2 = [1, 2, 3]

list3 = list1 + list2
print(list3)

list1.extend(list2)
print(list1)

append()	Adds an element at the end of the list

clear()	Removes all the elements from the list

copy()	Returns a copy of the list
count()	Returns the number of elements with the specified value

extend()	Add the elements of a list (or any iterable), to the end of the current list

index()	Returns the index of the first element with the specified value

insert()	Adds an element at the specified position

pop()	Removes the element at the specified position

remove()	Removes the item with the specified value

reverse()	Reverses the order of the list

sort()	Sorts the list

In [ ]:
#tuple ordered dupicate unchangable
thistuple = ("hello world")
this_tuple =("tell",5,"xam",True)
this__tuple= tuple(("hello","world"))

In [ ]:
#tuple are unchangable thsu we are changing it into list frst 
#and changin it into tupl back after converting
x = ("apple", "banana", "cherry")
y = list(x)
y[1] = "kiwi"
x = tuple(y)
print(x)

#tuple1=tuple2+tuple3 is possible
#mytuple=tuple1*2

fruits = ("apple", "banana", "cherry")
(green, yellow, red) = fruits
print(green)
print(yellow)
print(red)

#if the number of items vary then we can use asterisk*
fruits = ("apple", "mango", "papaya", "pineapple", "cherry")
(green, *tropic, red) = fruits

('apple', 'kiwi', 'cherry')
apple
banana
cherry

In [ ]:
#set is unordered unchangable unindexed unduplicative here True and 1 are same thus duplicative
thisset = {"abc", 34, True, 40, "male"}
#set item values cant be changed but it added or deleted
#set() constructor is available
thisset.add("orange")
thisset = {"apple", "banana", "cherry"}
tropical = {"pineapple", "mango", "papaya"}

thisset.update(tropical)

thisset = {"apple", "banana", "cherry"}
mylist = ["kiwi", "orange"]
#adding list elements to a set
thisset.update(mylist)

In [ ]:

#in set index removal isn't possible
set.pop()
del set
set.clear()
set.remove("item")

In [ ]:
set1.union(set2) # same as adding have all the distinct values
#The intersection() method will return a new set, that only contains the items that are present in both sets.
set1.intersection(set2)#gives only the common values
#The symmetric_difference() method will return a new set, that contains only the elements that are NOT present in both sets.
set1.symmetric_difference(set2)

isdisjoint()	Returns whether two sets have a intersection or not

issubset()	Returns whether another set contains this set or not

issuperset()	Returns whether this set contains another set or not

In [ ]:
#Dictionary items are ordered, changeable, and does not allow duplicates.

#Duplicate values will overwrite existing values:

thisdict = {
  "brand": "Ford",
  "electric": False,
  "year": 1964,
  "colors": ["red", "white", "blue"]
}
#all datatypes are supported

thisdict_ = dict(name = "John", age = 36, country = "Norway")
print(thisdict)
x = thisdict.keys()
print(x) #gives keys present in the dictionary
y = thisdict.values()
print(y) # gives values present in the dictionary
z = thisdict.items()
print(z)#it will give a list in which each key value pair is stated as tuple
#thisdict.update({"year": 2020}) # used as a insert into the dictionary else 
#other methods are also used
thisdict["color"] = "red"
thisdict.pop("year")

{'brand': 'Ford', 'electric': False, 'year': 1964, 'colors': ['red', 'white', 'blue']}
dict_keys(['brand', 'electric', 'year', 'colors'])
dict_values(['Ford', False, 1964, ['red', 'white', 'blue']])
dict_items([('brand', 'Ford'), ('electric', False), ('year', 1964), ('colors', ['red', 'white', 'blue'])])

1964

In [ ]:
#loop through dictionary
for i in dict: #prints keys
for i in dict.keys(): #prints keys
for i in dict.values(): #prints values
for x,y in dict: #prints x=keys and y= values

In [ ]:
mydict = thisdict.copy() # copyinf dcit to another dict
mydict = dict(thisdict) # dict() constructor is used to change into dict

In [ ]:
#nested dict
myfamily = {
  "child1" : {
    "name" : "Emil",
    "year" : 2004
  },
  "child2" : {
    "name" : "Tobias",
    "year" : 2007
  },
  "child3" : {
    "name" : "Linus",
    "year" : 2011
  }
}

print(myfamily["child2"]["name"])

Tobias

In [ ]:
if a > b: print("a is greater than b") # short if
print("A") if a > b else print("B") #short if else
if a > b and c > a:
if a > b or a > c:
if not a > b:
   print("a is NOT greater than b")

 pass #let it continue
 break#breaks the flow

In [ ]:
while i < 6:
  i += 1
  if i == 3:
    continue #continue we can stop the current iteration, and continue with the next:

In [ ]:
#Even strings are iterable objects, they contain a sequence of characters:
#Loop through the letters in the word "banana":
for x in "banana":
  print(x)

for x in range(6):#range(6) is not the values of 0 to 6, but the values 0 to 5.
#The range() function defaults to increment the sequence by 1, however it is possible to specify the increment value by adding a third parameter: range(2, 30, 3):

In [5]:
#fucntion
def funct():
  print ("hello")
funct()

def my_function(fname, lname):
  print(fname + " " + lname)

my_function("Emil", "Refsnes")

#when the number of vaariables is more than expected
def hell(*kids):
  print("hello"+kids[2])
hell("sar","car","van","mus")

#when the number of keyword arguments is more than expected we use **kwargs
def my_func(**kid):
  print("his last name is"+kid["lname"])
my_func(lname="shiva",kname="sk")

#default parameter
def my(country="norway"):
  print("i am from"+country)
my()

def my_functin(food):
  for x in food:
    print(x)
fruits = ["apple", "banana", "cherry"]
#passing list as input
my_functin(fruits)

hello
Emil Refsnes
hellovan
his last name isshiva
i am fromnorway
apple
banana
cherry

In [ ]:
x = lambda a: a+10
y = lambda a,b :a*b
z = lambda a,b,c: a+b+c
print(x(5))
print(y(5,8))
print(z(4,6,2))

#lambda is usd more properly and neccesary in functions

def func(n):
  return lambda a : a*n
double = func(2)
triple = func(3)

print(double(11))
print(triple(11))

to use LISTS as ARRAYS, however, to work with arrays in Python you will have to import a library, like the NumPy library.

cars = ["Ford", "Volvo", "BMW"]
It has all the methods that of a list data type

In [6]:
#classses &o objects
class hell:
  x=5
o1 =hell()
print(o1.x)

#All classes have a function called __init__(),
# which is always executed when the class is being initiated.

class pieces:
  def __init__(self,name,age):
    self.name = name
    self.age =age
p1 = pieces("john",35)

print(p1.name)
print(p1.age)

5
john
35

In [9]:
class preson:
  def __init__(self,name,age):
    self.name = name
    self.age = age

  def myfunc(self):
    print("hello"+self.name)
p1 = preson("santy",20)
p1.myfunc()

hellosanty

In [ ]:
p1.age = 40
del p1.age
del p1
#deletion and assigning values

In [12]:
class present:
  def __init__(self,name,age):
    self.name = name
    self.age = age
  def pri(self):
    print(self.name,self.age)
x = present("santy",20)
x.pri()

class child(present):
  pass

y = child("mike",10)
y.pri()

santy 20
mike 10

In [ ]:
#When you add the __init__() function, the child class will no longer inherit the parent's __init__() function.
#The child's __init__() function overrides the inheritance of the parent's __init__() function.
#To keep the inheritance of the parent's __init__() function, add a call to the parent's __init__() function:
class Student(Person):
  def __init__(self, fname, lname):
    Person.__init__(self, fname, lname) # it can also be written as
    super().__init__(fname,lname)

In [13]:
class Person:
  def __init__(self, fname, lname):
    self.firstname = fname
    self.lastname = lname

  def printname(self):
    print(self.firstname, self.lastname)

class Student(Person):
  def __init__(self, fname, lname, year):
    super().__init__(fname, lname)
    self.graduationyear = year

x = Student("Mike", "Olsen", 2019)
print(x.graduationyear)

2019

In [ ]:
#iterator
mytuple = ("apple", "banana", "cherry")
myit = iter(mytuple)

print(next(myit))
print(next(myit))
print(next(myit))

mystr = "banana"
myit = iter(mystr)

print(next(myit))
print(next(myit))
print(next(myit))
print(next(myit))
print(next(myit))
print(next(myit))

mytuple = ("apple", "banana", "cherry")

for x in mytuple:
  print(x)

#To create an object/class as an iterator you have to implement the methods __iter__() and __next__() to your object.
#The __iter__() method acts similar, you can do operations (initializing etc.), but must always return the iterator object itself.
#The __next__() method also allows you to do operations, and must return the next item in the sequence.

class MyNumbers:
  def __iter__(self):
    self.a = 1
    return self

  def __next__(self):
    x = self.a
    self.a += 1
    return x
#StopIteration
myclass = MyNumbers()
myiter = iter(myclass)

print(next(myiter))
print(next(myiter))
print(next(myiter))
print(next(myiter))
print(next(myiter))

In [ ]:
#If you use the global keyword, the variable belongs to the global scope:
def func():
  global x
  x =300
func()
print(x)

#To change the value of a global variable inside a function, refer to the variable by using the global keyword:
x = 300
def myfunc():
  global x
  x = 200

myfunc()

print(x)

In [ ]:
#module
import mymodule
mymodule.greeting("Jonathan")

import mymodule as mx
a = mx.person1["age"]
print(a)
from mymodule import person1
print(person1["age"])





################Time Module is left#####################

In [ ]:
#in built math module
x = min(5, 10, 25)
y = max(5, 10, 25)
x = abs(-7.25)
x = pow(4, 3)
x = math.sqrt(64)

import math as sq
#Round a number upward to its nearest integer
x = sq.ceil(1.4)

#Round a number downward to its nearest integer
y = sq.floor(1.4)

print(x)
print(y)

z = math.pi #3.14

###############JSON module is left#############

In [ ]:
import re
txt = "the rain in spain"
x =re.search("spain",txt)
if x :
  print("yes! we have a match")
else:
  print("no match")

findall	Returns a list containing all matches

x = re.findall("ai", txt)

search	Returns a Match object if there is a match anywhere in the string

x = re.search("\s", txt)

split	Returns a list where the string has been split at each match

x = re.split("\s", txt)
x = re.split("\s", txt, 1)#splits only at the first occurence

sub	Replaces one or many matches with a string

x = re.sub("\s", "9", txt)
x = re.sub("\s", "9", txt, 2)#upto two positions

#.span() returns a tuple containing the start-, and end positions of the match.
#.string returns the string passed into the function
#.group() returns the part of the string where there was a match

txt = "The rain in Spain"
x = re.search(" S", txt)
print(x.span())
print(x.string)
print(x.group())

In [ ]:
#The try block lets you test a block of code for errors.

#The except block lets you handle the error.

#The else block lets you execute code when there is no error.

#The finally block lets you execute code, regardless of the result of the try- and except blocks.

try:
  print(x)
except NameError:
  print("Variable x is not defined")
except:
  print("Something else went wrong") #many exceptions can be created

try:
  print("Hello")
except:
  print("Something went wrong")
else:
  print("Nothing went wrong")# nothing went wrong means this runs and try doesnt throw an error
finally:
  print("The 'try except' is finished")#prints regardless of there is an error or not

#nested try except
try:
  f = open("demofile.txt")
  try:
    f.write("Lorum Ipsum")
  except:
    print("Something went wrong when writing to the file")
  finally:
    f.close()
except:
  print("Something went wrong when opening the file")

raise Exception("Sorry, no numbers below zero") # raise throws a error voulntarily
raise TypeError("Only integers are allowed")#error type can be specified during error exception

In [2]:
#Format the price to be displayed as a number with two decimals:

txt = "The price is {:.2f} dollars"
quantity = 3
itemno = 567
price = 49
myorder = "I want {} pieces of item number {} for {:.2f} dollars."
print(myorder.format(quantity, itemno, price))
myorder = "I want {0} pieces of item number {1} for {2:.2f} dollars."
print(myorder.format(quantity, itemno, price))
myorder = "I have a {carname}, it is a {model}."
print(myorder.format(carname = "Ford", model = "Mustang"))

I want 3 pieces of item number 567 for 49.00 dollars.
I want 3 pieces of item number 567 for 49.00 dollars.
I have a Ford, it is a Mustang.

The key function for working with files in Python is the open() function.


The open() function takes two parameters; filename, and mode.


There are four different methods (modes) for opening a file:


"r" - Read - Default value. Opens a file for reading, error if the file does not exist


"a" - Append - Opens a file for appending, creates the file if it does not exist


"w" - Write - Opens a file for writing, creates the file if it does not exist


"x" - Create - Creates the specified file, returns an error if the file exists


In addition you can specify if the file should be handled as binary or text mode


"t" - Text - Default value. Text mode


"b" - Binary - Binary mode (e.g. images)

In [ ]:
f = open("demofile.txt", "r")
print(f.read())
f = open("D:\\myfiles\welcome.txt", "r") #if the file isnt located near
print(f.read())
f =open("demofile.txt","r")
print(f.read(5))
print(f.readline())
f.close()

#it appends the data to the file
f = open("demofile2.txt", "a")
f.write("Now the file has more content!")
f.close()

#it overwrites the data
f = open("demofile3.txt", "w")
f.write("Woops! I have deleted the content!")
f.close()

#Create a file called "myfile.txt":
f = open("myfile.txt", "x")
#Result: a new empty file is created!

To delete a file, you must import the OS module, and run its os.remove() function:

import os
os.remove("demofile.txt")

if os.path.exists("demofile.txt"):
  os.remove("demofile.txt")
else:
  print("The file does not exist")
  

os.rmdir("myfolder") #Remove the folder "myfolder":